### ISSUE TITLE
No arg_max in KITTI_train_ICRs.yml file

### ISSUE THREAD

**Issue by adamanov** [Nicholasli1995/EgoNet#8]
Hello, firstly I would like to thanks for an amazing work and that you made it public with great documentation in order to reproduce and re train the network.

Today I wanted to train your network according to [training - stage2](https://github.com/Nicholasli1995/EgoNet/blob/master/docs/training.md#stage-2-train-the-remaining-part-hcpth). However, by running the code I got an error as following 
```
$ python train_IGRs.py --cfg "../configs/KITTI_train_IGRs.yml"

=> init weights from normal distribution
=> loading pretrained model ../resources/start_point.pth

Total Parameters: 63,978,471
----------------------------------------------------------------------------------------------------------------------------------
Total Multiply Adds (For Convolution and Linear Layers only): 19.573845863342285 GFLOPs
----------------------------------------------------------------------------------------------------------------------------------
Number of Layers
Conv2d : 306 layers   BatchNorm2d : 304 layers   ReLU : 269 layers   Bottleneck : 4 layers   BasicBlock : 108 layers   Upsample : 28 layers   HighResolutionModule : 8 layers   Sigmoid : 1 layers   
Initializing KITTI train set, please wait...
Found prepared keypoints at ../kitti_dataset/training/keypoints/bbox9[0.332, 0.667]_train_['Car'].npy
Found prepared instance_ids at ../kitti_dataset/training/keypoints/bbox9[0.332, 0.667]_train_['Car']_ids.npy
Found prepared rotations at ../kitti_dataset/training/keypoints/bbox9[0.332, 0.667]_train_['Car']_rots.npy
Initialization finished for KITTI train set
Initializing KITTI valid set, please wait...
Found prepared keypoints at ../kitti_dataset/training/keypoints/bbox9[0.332, 0.667]_valid_['Car'].npy
Found prepared instance_ids at ../kitti_dataset/training/keypoints/bbox9[0.332, 0.667]_valid_['Car']_ids.npy
Found prepared rotations at ../kitti_dataset/training/keypoints/bbox9[0.332, 0.667]_valid_['Car']_rots.npy
Initialization finished for KITTI valid set
Traceback (most recent call last):
  File "train_IGRs.py", line 159, in <module>
    main()
  File "train_IGRs.py", line 154, in main
    train(model, model_settings, GPUs, cfgs, logger, final_output_dir)
  File "train_IGRs.py", line 89, in train
    trainer.train(train_dataset=train_dataset, 
  File "../libs/trainer/trainer.py", line 154, in train
    evaluator = Evaluator(cfgs['training_settings']['eval_metrics'], 
  File "../libs/metric/criterions.py", line 546, in __init__
    self.metrics.append(eval(metric + '(cfgs=cfgs, num_joints=num_joints)'))
  File "<string>", line 1, in <module>
  File "../libs/metric/criterions.py", line 183, in __init__
    self.arg_max = cfgs['testing_settings']['arg_max']
KeyError: 'arg_max
```

It seems that **arg_max** key is missing in the [ KITTI_train_IGRs.yml](https://github.com/Nicholasli1995/EgoNet/blob/4c8386b7043fc8e2e44da81889b2837988e35f1d/configs/KITTI_train_IGRs.yml#L176)

How to **arg_max** parameter should be defined?

Thanks for answer in advance.

**Comment by adamanov** [comment]
by editing KITTI_train_IGRs.yml file and including in a line 186 `arg_max: 'hard' `parameter, the problem will be solved.
